name: Publish TMLSPEC CLI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish package
        uses: Time-Machine-Lab/TML-Github_Actions/actions/publish-node-package@main
        with:
          cache_dependency_path: TMLSPEC-cli/package-lock.json
          node_version: '20.x'
          working_directory: TMLSPEC-cli
          build_command: npm run build
          publish_command: npm publish
          tag_prefix: v
          registry_url: ${{ secrets.NPM_REGISTRY_URL }}
          npm_token: ${{ secrets.NPM_TOKEN }}
